# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-07 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=10)),
                ('login_count', models.IntegerField()),
                ('project_count', models.IntegerField()),
            ],
        ),
    ]
